# Generated by Django 4.1.5 on 2023-01-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patientlist',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientList',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
