# Generated by Django 4.1.5 on 2023-01-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_patient_patientlist_delete_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sf36_raw',
            name='data_wypelnienia',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pacjenci',
            name='pacjent_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
