# Generated by Django 4.1.5 on 2023-01-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sf36_raw_data_wypelnienia_alter_pacjenci_pacjent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='sf36_recoded',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.sf36_raw')),
                ('funkcjonowanie_fizycznie', models.IntegerField()),
                ('ograniczenie_fizycznie', models.IntegerField()),
                ('ograniczenie_emocjonalne', models.IntegerField()),
                ('dolegliwosci_bolowe', models.IntegerField()),
                ('poczucie_zdrowia_ogolne', models.IntegerField()),
                ('witalnosc', models.IntegerField()),
                ('funkcjonowanie_spoleczne', models.IntegerField()),
                ('poczucie_zdrowia_psychicznego', models.IntegerField()),
            ],
        ),
    ]
